version: '2'
services:
  app:
    build: app
    volumes:
      - ~/Dropbox/var/tdiary-data:/usr/src/app/data
      - ~/Dropbox/var/tdiary-public:/usr/src/app/public
    restart: always
  web:
    build: web
    volumes_from:
      - app
    ports:
      - "8080:80"
    restart: always
