agent:
  image: mackerel/mackerel-agent
  hostname: conoha
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/mackerel-agent/:/var/lib/mackerel-agent/
  environment:
    apikey:
    enable_docker_plugin: 'true'
    auto_retirement: 'false'
    opts: -v
  restart: always
